<?php
/**
 * This file is part of payjp4
 *
 * Copyright(c) Akira Kurozumi <info@a-zumi.net>
 *
 *  https://a-zumi.net
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\payjp4\Tests\Form\Admin;


use Eccube\Tests\Form\Type\AbstractTypeTestCase;
use Plugin\payjp4\Form\Type\Admin\ConfigType;
use Symfony\Component\Form\FormInterface;

class ConfigTypeTest extends AbstractTypeTestCase
{
    /**
     * @var FormInterface
     */
    protected $form;

    protected $formData = [
        'public_key' => 'dummy',
        'secret_key' => 'dummy'
    ];

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->form = $this->formFactory
            ->createBuilder(ConfigType::class, null, [
                'csrf_protection' => false
            ])
            ->getForm();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test正しいデータ()
    {
        $this->form->submit($this->formData);
        self::assertTrue($this->form->isValid());
    }

    public function testPublicKeyが空白のときはエラー()
    {
        $this->formData['public_key'] = '';
        $this->form->submit($this->formData);
        self::assertFalse($this->form->isValid());
    }

    public function testSecretKeyが空白のときはエラー()
    {
        $this->formData['secret_key'] = '';
        $this->form->submit($this->formData);
        self::assertFalse($this->form->isValid());
    }
}
