<?php
/**
 * This file is part of payjp4
 *
 * Copyright(c) Akira Kurozumi <info@a-zumi.net>
 *
 *  https://a-zumi.net
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\payjp4\Tests\Form\Type\Admin;


use Eccube\Entity\Master\SaleType;
use Eccube\Entity\ProductClass;
use Eccube\Form\Type\Admin\ProductClassEditType;
use Eccube\Tests\Form\Type\AbstractTypeTestCase;
use Symfony\Component\Form\FormInterface;

class ProductClassEditTypeTest extends AbstractTypeTestCase
{
    /**
     * @var FormInterface
     */
    protected $form;

    /**
     * @var SaleType
     */
    protected $saleType;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->form = $this->formFactory
            ->createBuilder(ProductClassEditType::class, null, ['csrf_protection' => false])
            ->getForm();

        $this->saleType = $this->entityManager->getRepository(SaleType::class)
            ->findOneBy([
                'name' => trans('plugin.payjp.admin.sale_type.name')
            ]);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test販売種別が定期購入の場合エラーになるか()
    {
        $this->form->submit(["sale_type" => $this->saleType->getId()]);
        self::assertFalse($this->form->isValid());
    }
}
