<?php
/**
 * This file is part of payjp4
 *
 * Copyright(c) Akira Kurozumi <info@a-zumi.net>
 *
 *  https://a-zumi.net
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\payjp4\Tests\Web\Admin;


use Eccube\Common\Constant;
use Eccube\Tests\Web\Admin\AbstractAdminWebTestCase;
use Symfony\Component\Filesystem\Filesystem;

class ConfigControllerTest extends AbstractAdminWebTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testPAYJP情報を保存したらenvファイルに情報が追記されるか()
    {
        $container = self::$kernel->getContainer();
        $envFile = $container->getParameter('kernel.project_dir') . '/.env';

        $fs = new Filesystem();
        $fs->copy($envFile, $envFile . '.backup');

        $this->client->request('POST', $this->generateUrl('payjp_admin_config'), [
            'config' => [
                'public_key' => 'dummy',
                'secret_key' => 'dummy',
                'webhook_token' => 'dummy',
                Constant::TOKEN_NAME => 'dummy'
            ]
        ]);

        $env = file_get_contents($envFile);

        $keys = [
            'PAYJP_PUBLIC_KEY',
            'PAYJP_SECRET_KEY'
        ];

        foreach ($keys as $key) {
            $pattern = '/^(' . $key . ')=(.*)/m';
            if (preg_match($pattern, $env, $matches)) {
                self::assertEquals('dummy', $matches[2]);
            } else {
                self::fail(sprintf("%sが見つかりませんでした。", $key));
            }
        }

        // envファイルを戻す
        $fs->rename($envFile . '.backup', $envFile, true);
    }
}
