<?php
/**
 * This file is part of payjp4
 *
 * Copyright(c) Akira Kurozumi <info@a-zumi.net>
 *
 *  https://a-zumi.net
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\payjp4\Tests\Service\PurcaseFlow\Processor;


use Eccube\Entity\Master\OrderStatus;
use Eccube\Entity\Order;
use Eccube\Entity\Payment;
use Eccube\Service\PurchaseFlow\PurchaseContext;
use Eccube\Tests\EccubeTestCase;
use Plugin\payjp4\Entity\PaymentStatus;
use Plugin\payjp4\Service\Method\CreditCard;
use Plugin\payjp4\Service\PurchaseFlow\Processor\OrderUpdateProcessor;

class OrderUpdateProcessorTest extends EccubeTestCase
{
    /**
     * @var OrderUpdateProcessor
     */
    protected $processor;

    /**
     * @var Order
     */
    protected $Order;

    /**
     * @var Payment
     */
    protected $Payment;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->processor = new OrderUpdateProcessor(
            $this->entityManager->getRepository(OrderStatus::class),
            $this->entityManager->getRepository(PaymentStatus::class),
            $this->entityManager->getRepository(Payment::class)
        );

        $this->Order = $this->createOrder($this->createCustomer());
        $this->Payment = $this->entityManager->getRepository(Payment::class)->findOneBy([
            'method_class' => CreditCard::class
        ]);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testNewInstance()
    {
        self::assertInstanceOf(OrderUpdateProcessor::class, $this->processor);
    }

    public function testPrepare()
    {
        $this->Order->setPayment($this->Payment);
        $this->processor->prepare($this->Order, new PurchaseContext());
        self::assertEquals(OrderStatus::PENDING, $this->Order->getOrderStatus()->getId());
        self::assertEquals(PaymentStatus::OUTSTANDING, $this->Order->getPayJpPaymentStatus()->getId());
    }

    public function testCommit()
    {
        $this->Order->setPayment($this->Payment);
        $this->processor->commit($this->Order, new PurchaseContext());
        self::assertEquals(OrderStatus::NEW, $this->Order->getOrderStatus()->getId());
        self::assertEquals(PaymentStatus::ACTUAL_SALES, $this->Order->getPayJpPaymentStatus()->getId());
    }

    public function testRollback()
    {
        $this->Order->setPayment($this->Payment);
        $this->processor->rollback($this->Order, new PurchaseContext());
        self::assertEquals(OrderStatus::PROCESSING, $this->Order->getOrderStatus()->getId());
        self::assertEquals(PaymentStatus::OUTSTANDING, $this->Order->getPayJpPaymentStatus()->getId());
    }
}
